version: '2'

services:
    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "8085:8085/udp"
        volumes: 
            - "./inputs/tcp-input.conf:/etc/logstash/conf.d/tcp-input.conf"
            - "./outputs/30-output.conf:/etc/logstash/conf.d/30-output.conf"
        environment: 
            - "LS_OPTS=--config.reload.automatic"