version: '2.1'

services:
    elk:
        
        image: galtrold/propellerlogger
        
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "8085:8085/udp"
        volumes: 
            #- "./propeller-input.conf:/etc/logstash/conf.d/tcp-input.conf"
            - "c:/WebSites/propeller.mvc/Website/:/var/www"
        environment: 
            - "LS_OPTS=--config.reload.automatic"
            - "doMerge=false"
            